spring:
    profiles:
        active: dev
    datasource:
        url: jdbc:mysql://localhost:3306/yondu_wiki
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQL57Dialect
logging:
    level:
        "[org.springframework.web]":
rsa:
    public-key: classpath:rsa/public.pem
    private-key: classpath:rsa/private.pem
